repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*'
        args: [
            '--line-length=120',
            '--multi-line=3',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args: [
            '--max-line-length=110',
        ]
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files
      -   id: check-merge-conflict
      -   id: check-ast
      -   id: debug-statements
      -   id: check-toml
      -   id: check-json
      -   id: check-xml
